import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='flex items-center'>
          <div className="flex items-center justify-between font-mono px-4 py-1 hover:text-blue-300">
            <Link href="/">Home</Link>
          </div>
          <div className="flex items-center justify-between font-mono px-4 py-1  hover:text-blue-300">
            <Link href="/dashboard">Dashboard</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
